### ISSUE TITLE
need access to dhcp settings (network?)

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#13] opened 2016-11-13 15:49 UTC
If worst comes to worst, we need to be able to replace a box with another one. This means basicly dropping in a mac/ip mapping in the dhcp server and running ansible.

We want to rely on a quick response from the network team for this. Needs coordination with network...

**Comment by RichiH** [comment] 2016-11-13 19:58
I think you will maintain that file in our repo. That way we can pull it
when you change.

Richard

Sent by mobile; excuse my brevity.

**Comment by gerryd** [comment] 2017-01-25 22:03
Duplicate of #58

**Closed by gerryd** 2017-01-25 22:03 UTC
